### ISSUE TITLE
ModuleNotFoundError upon attempting to activate addon

### ISSUE THREAD

**Issue by Lights-and-Shadows** [mitsuba-renderer/mitsuba2-blender#5]
Hey folks,

After following the documentation for configuring and compiling the renderer, I'm now at the stage of setting up the addon for Blender to be able to use it. However, each time I try to activate the addon, it keeps throwing this:
![image](https://user-images.githubusercontent.com/36210321/85229627-dceb8b80-b3b8-11ea-817b-c6d73f227d2b.png)

This is effectively stopping my progress for the time being. Is there something I need to modify perhaps?

This is on a Windows 10 x64 machine, used Python 3.7x. I had the same situation happen on my Windows 7 x64 machine that used Miniconda (pretty much an exact duplicate of the documentation's process except for the operating system)

**Comment by Lights-and-Shadows** [comment]
Solved it. I replaced the "." between 0 and 1 in the version number section of the folder's name with a "-" and it works fine.

**Comment by bathal1** [comment]
Interesting! did you add this "0.1" yourself? If not, this is something we need to take care of.

**Comment by Lights-and-Shadows** [comment]
I did have to manually change the numbers, yes.
________________________________

**Comment by ALLIESXO** [comment]
@bathal1 
When downloading the .zip file from the [**release list**](https://github.com/mitsuba-renderer/mitsuba2-blender/releases) the naming of the zip is "mitsuba2-blender-0.1.zip" by default, which leads to the error of this issue.
When downloading the zip file from master branch the naming is different so no errors occur. 

In order to avoid this issue in future, the releases should have a different version naming (without dot in between).

**Comment by bathal1** [comment]
Thanks for bringing this up! There is now a zip file with the proper name in the release file.
